### ISSUE TITLE
Results in current directory

### ISSUE THREAD

**Issue by anadj-micro** [jsevo/taxumap#11]
Results should be placed in phylo-umap/results folder, but that doesn't happen. All the logs and embedding.csv is in the working directory.

**Comment by granthussey** [comment]
I think having results outputted into the current working directory should be expected behavior. I.e., if someone is working on a notebook and runs `tu.save_embedding()` function, the results should be expected to be saved to the current working directory of the notebook itself.

@jsevo , do you have an opinion about this?

**Comment by jsevo** [comment]
I agree. But the documentation or API (can't remember which) claimed
incorrectly that they are put into "results/"

**Comment by granthussey** [comment]
Ok cool, I will adjust accordingly.

**Comment by granthussey** [comment]
Fixed in #19
