### ISSUE TITLE
Taxumap.scatter() throws an error 

### ISSUE THREAD

**Issue by jsevo** [jsevo/taxumap#13]
Likely because the embedding is now stored as np.array ( .embedding) and dataframe with data like index ( .df_embedding). 
<img width="1064" alt="Screen Shot 2022-01-27 at 1 56 25 PM" src="https://user-images.githubusercontent.com/5849690/151425531-6342bfd4-9463-40a8-8397-55b746af06f5.png">

**Comment by granthussey** [comment]
`self.taxumap1` and `self.taxumap2` were an attribute of the `Taxumap` object for labels of the scatterplot. Since we have different `agg_level` schemes, `self.taxumap1` and `self.taxumap2` would mirror this. For example, ['Phylum', 'Family'] would be called `taxumap1-PF` and `taxumap2-PF`. 

It seems these attributes are not properly "mixing in" to the `Taxumap` object. Fixing now.

The commit where you changed the files around so that we import `taxumap_base` seemed to remove inserting from the TaxUMAP mixins.

**Comment by granthussey** [comment]
Hmm ..  I don't know _where_ the error happened but fixing it regardless.

**Comment by granthussey** [comment]
Fixed in d99d96a131aec3897eb0c8d8132eada3fd066ae5

**Comment by granthussey** [comment]
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/16183823/152833916-a4cf1d78-0064-4e14-b2b8-399b4b0cd282.png">
